# Generated by Django 4.2.6 on 2023-10-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_order_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('qtde', models.IntegerField(default=0)),
                ('id_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.products')),
            ],
        ),
    ]
