# Generated by Django 4.2.6 on 2023-10-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_inventory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='id_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.products'),
        ),
    ]
