# Generated by Django 4.2.6 on 2023-10-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_inventory_id_alter_inventory_id_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Delivery_Pickup',
            field=models.CharField(default='Delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='time_delivery',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
